//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Main.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_LOGIN_DIALOG                102
#define IDD_SIGNUP_DIALOG               103
#define IDD_HOMECHAT_DIALOG             132
#define IDD_CHATFRIEND_DIALOG           134
#define IDC_STATIC_LOGIN_TITLE          1000
#define IDC_STATIC_LOGIN_USERNAME       1001
#define IDC_STATIC_LOGIN_PASSWORD       1002
#define IDC_EDIT_LOGIN_USERNAME         1003
#define IDC_EDIT_LOGIN_PASSWORD         1004
#define IDC_CHK_LOGIN_REMEMBER          1005
#define IDC_BTN_LOGIN_SUBMIT            1006
#define IDC_STATIC_LOGIN_GOTO_SIGNUP    1007
#define IDC_STATIC_LOGIN_ERROR          1008
#define IDC_EDIT_SIGNUP_FULLNAME        1010
#define IDC_STATIC_SIGNUP_FULLNAME      1011
#define IDC_STATIC_SIGNUP_USERNAME      1012
#define IDC_EDIT_SIGNUP_USERNAME        1013
#define IDC_BUTTON_SIGNUP_SUBMIT        1014
#define IDC_STATIC_SIGNUP_ERROR         1015
#define IDC_STATIC_HOMECHAT_TITLE       1016
#define IDC_STATIC_HOMECHAT_FULLNAME    1017
#define IDC_STATIC_SIGNUP_PASSWORD      1018
#define IDC_EDIT_HOMECHAT_SEARCH        1019
#define IDC_EDIT_SIGNUP_PASSWORD        1020
#define IDC_STATIC_HOMECHAT_ERROR       1021
#define IDC_STATIC_SIGNUP_REPASS        1022
#define IDC_STATIC_HOMECHAT_DSBB        1023
#define IDC_EDIT_SIGNUP_REPASS          1024
#define IDC_EDIT_CHATFRIEND_MSG         1025
#define IDC_STATIC_CHATFRIEND_ERROR     1026
#define IDC_STATIC_CHATFRIEND_LT        1027
#define IDC_EDIT_CHATFRIEND_SEND        1028
#define IDC_STATIC_CHATFRIEND_FULLNAME  1029
#define IDC_STATIC_HOMECHAT_AVT         1030
#define IDC_STATIC_CHATFRIEND_SEND      1031
#define IDC_STATIC_HOMECHAT_FRIENDAREA  1032
#define IDC_STATIC_CHATFRIEND_EMOJI     1033
#define IDC_STATIC_CHATFRIEND_CHATAREA  1034
#define IDC_STATIC_CHATFRIEND_IMAGE     1035
#define IDC_STATIC_CHATFRIEND_ATTACH    1036
#define ID_LOGIN_TRIGGER                1101
#define ID_SIGNUP_TRIGGER               1102
#define ID_HOMECHAT_TRIGGER             1103
#define ID_CHATFRIEND_TRIGGER           1104

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
